# mkdocs.yml

site_name: casperbot.net
site_url: https://www.casperbot.net
repo_name: caspernet

nav:
  - Home: index.md
  - Add to Discord: add-discord.md
  - Wiki:
      - Overview: wiki/overview.md
      - Deep Dive: wiki/deep-dive.md
  - Contact: contact.md

docs_dir: src
site_dir: docs

# Your custom CSS file (relative to src/)
extra_css:
  - assets/css/extra.css

theme:
  name: material

  # Color palette
  palette:
    primary: indigo
    accent: teal

  # Always show all sidebar sections expanded
  features:
    - navigation.sections
    - navigation.expand

  # Fonts
  font:
    text: Roboto
    code: Roboto Mono

markdown_extensions:
  - admonition
  - toc:
      permalink: true