# mkdocs.yml

site_name: casperbot.net
site_url: https://www.casperbot.net
repo_name: caspernet

# ─────────────────────────────────────────────────
# NAVIGATION (now turned into top‑of‑page TABS)
# ─────────────────────────────────────────────────
nav:
  - Home: index.md
  - Wiki:
      - Overview: wiki/overview.md
      - Deep Dive: wiki/deep-dive.md
      - Commands: wiki/commands.md
  - Add to Discord: add-discord.md
  - Contact: contact.md

docs_dir: src
site_dir: docs

theme:
  name: material

  # ─────────────────────────────────────────────────
  # FEATURES
  # ─────────────────────────────────────────────────
  features:
    - navigation.tabs       # turn the nav keys into horizontal tabs
    - navigation.sections   # group by folder (enables dropdown)
    - navigation.expand     # never auto‑collapse your Wiki dropdown

  # ─────────────────────────────────────────────────
  # COLOR PALETTE (used for buttons, links, etc.)
  # ─────────────────────────────────────────────────
  palette:
    primary: indigo
    accent: teal

  # ─────────────────────────────────────────────────
  # FONTS
  # ─────────────────────────────────────────────────
  font:
    text: Roboto
    code: Roboto Mono

# Pull in our custom CSS to override hero background
extra_css:
  - assets/css/extra.css

# Any Markdown extensions you like
markdown_extensions:
  - admonition
  - toc:
      permalink: true