# mkdocs.yml

site_name: CasperBot
site_url: https://www.casperbot.net
repo_name: caspernet

nav:
  - Home: index.md
  - Wiki:
      - Overview: wiki/overview.md
      - Deep Dive: wiki/deep-dive.md
      - Commands: wiki/commands.md
  - Add to Discord: add-discord.md
  - Contact: contact.md

docs_dir: src
site_dir: docs

theme:
  name: material

  features:
    - navigation.tabs       # horizontal tabs at top (Wiki becomes a dropdown)
    # no navigation.sections/expand needed for a pure tab dropdown

  palette:
    primary: indigo
    accent: teal

  font:
    text: Roboto
    code: Roboto Mono

# our custom CSS to size & style the hero
extra_css:
  - assets/css/extra.css

markdown_extensions:
  - admonition
  - toc:
      permalink: true