# .github/workflows/deploy-docs.yml
name: Deploy docs → gh-pages

# 1) Give write access to contents so that GITHUB_TOKEN can push
permissions:
  contents: write

on:
  push:
    branches:
      - main
    # optional: only run when docs/ actually changes
    # paths:
    #   - 'docs/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 2) Checkout with persisted credentials
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      # 3) Push docs/ → root of gh-pages
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          publish_dir: docs
          # this token now has write-permissions
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user_name: github-actions
          user_email: github-actions[bot]@users.noreply.github.com
