# .github/workflows/build‑docs.yml
name: Build & Publish Docs

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'mkdocs.yml'

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true   # so we can push back
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install MkDocs & Material theme
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material

      - name: Build site
        run: mkdocs build --clean   # outputs into docs/

      - name: Commit & Push updated docs/
        uses: EndBug/add-and-commit@v7
        with:
          author_name: github-actions
          author_email: github-actions[bot]@users.noreply.github.com
          message: "chore: rebuild docs from src"
          add: 'docs/**'